### ISSUE TITLE
GPS-module

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#1]
**Depends on raspberry pi version!**

This is a meta-issue were we'll discuss which GPS-module to use and all issues concerning the GPS we'll be referenced here. When we're done, we'll close this issue.

*Create separate issues when necessary.*

Things that need to be discussed:

* Which GPS module to buy?
    * I've added the one we talked about during the meeting.
    * Confirm with HiQ that they accept to buy the specific module.
* Do we need / want an antenna?
    * Is it possible, when it's flying?
* Installation of the module
   * The guide recommends using a USB-to-TTL console cable.
   * Is a cable problematic with the drone? Cables might be in the way?
   * Try getting it to work.
   * Any volunteer?
* Any volunteer to write the GPS python code?
   * Start by printing interesting information. Speed, Long, Lat etc.
   * Followed by storing it in a local SQL database.
   * Followed by storing it in the cloud SQL database.
   * Done. 

References
-------------

GPS-module Breakout version product page:
https://www.adafruit.com/products/746

GPS-module HAT version product page:
http://www.adafruit.com/products/2324

Tutorial for our GPS-module:
https://learn.adafruit.com/adafruit-ultimate-gps-on-the-raspberry-pi/introduction

More example code:
http://www.stuffaboutcode.com/2013/09/raspberry-pi-gps-setup-and-python.html

USB-to-TTL console cable:
https://www.adafruit.com/products/954

**Comment by fellan12** [comment]
When it comes to which GPS-module we should buy, there is a few versions we could choose between. The one in the reference is Breakout version there we need to wire it ourselves. But there is a HAT version there we just kinda "plug and play" it. Which I recommend and saves us from some potential complications if something goes wrong in the wiring.

In addition it works for the pi 2 and it has a internal battery slot, which saves us some battery power on the GPS module.

The downside in the HAT version is that the HAT takes over the Raspberry Pi's hardware UART to send/receive data to and from the GPS module. So, if we need to use the RX/TX pins with a console cable, we cannot also use this HAT. Instead, we will have to use a composite or HDMI monitor and keyboard to log in, or use ssh to connect over the network to our Pi.

GPS module HAT version product page:
http://www.adafruit.com/products/2324

**Comment by fellan12** [comment]
What do you guys think?

**Comment by karlek** [comment]
With the internal battery for the HAT version, how much will it weigh?

**Comment by fellan12** [comment]
From what's decided yet:

Raspberry Pi 2 (Model B) : 42g (There is no exact weight for the Pi 2 i approximate around Pi B+) (http://www.adafruit.com/products/2358)
Case : 28g (http://www.adafruit.com/products/2285) 
GPS HAT version: 25g (There is no exact weight for the GPS HAT: But given the size and what's on it I approximate the weight less then a Pi 2, but more the a GPS Breakout, which has the weight of 8.5g)

The total weight for those components is: 95g

And with the battery pack (Which is not decided on yet): 140g (http://www.adafruit.com/products/1565) 
and the Wifi unit (Which is not decided on yet): 6g (http://www.adafruit.com/products/1012). 

then the total weight is: 241g

**Comment by karlek** [comment]
Looking good. Link the HAT version and all necessary cables, battery, etc. and then we can close this issue!

**Comment by fellan12** [comment]
Will do that!
But doesn't battery go under another issue?

**Comment by karlek** [comment]
I meant for the HAT version:
https://www.adafruit.com/products/380

**Comment by fellan12** [comment]
For the GPS there is no cable needed, only soldering. Which we can solve on the side.

So for the GPS unit we will buy the following:

GPS HAT Version: http://www.adafruit.com/products/2324
Internal battery for the GPS: https://www.adafruit.com/products/380
