### ISSUE TITLE
Graphical representation

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#10]
How should the collected data be graphically displayed?

Suggestions:
* We can display change in speed during different parts of the track, i.e. change of velocity over time. 
* Min, max and average velocity.
* Draw a path between from collected points onto a map.
   * Color the path in different colors depending on velocity or acceleration, e.g. slower = red, faster = green.
   * Paths from all laps at the same time, grayed out, to visualize the spread. Then they can be highlighted my selecting a track. 
  * Display individual snapshots of the drone's coordinates and status as points along the path. Hovering on a points displays the drone's status at that point.

**Comment by karlek** [comment]
@aronstrandberg Any update?

**Comment by nejlika** [comment]
The current prototyp can be found at:
http://aronstrandberg.com/drones/

**Comment by karlek** [comment]
Lol meta close this issue.
