### ISSUE TITLE
Install ruby on rails 

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#11]
Login credentials necessary for SSHing to the azure server:
```shell
$ ssh azureuser@mvk.cloudapp.net
```
the password is in slack. 

Any volunteer?

References
-------------
http://blogs.msdn.com/b/brunoterkaly/archive/2014/11/21/installing-ruby-on-rails-on-ubuntu-on-linux-on-azure.aspx#Adding_Ruby

**Comment by aronstrandberg** [comment]
Installed:

- Ruby 2.2.0
  - ruby-install
  - chruby
- Rails 4.2.0
- SQLite 3
- PostgreSQL

**Comment by karlek** [comment]
Sweet :camel:

**Comment by aronstrandberg** [comment]
Redundant now that we won't be using Rails
