### ISSUE TITLE
Test remote SQLite queries

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#12]
* Create a test database on the Azure.
* Create a test table on the Azure.
* Perform a quick and dirty INSERT query from your computer with a programming language of your choice, (PHP, Python, etc.).
*  Verify on the server that the database table has been updated.
* Smile :camel:

**Comment by karlek** [comment]
Depends on #11

**Comment by fellan12** [comment]
Okej, now that the #11 is done, I someone that knows ubuntu and basic knowledge of SQL.

any volunteers?

**Comment by fellan12** [comment]
Aron is now assigned to do this Test.

**Comment by aronstrandberg** [comment]
kommer inte hinna göra detta den här veckan så bättre om någon annan kan fixa

**Comment by nejlika** [comment]
Martin, Sandra and Agnes are all available according to the project planning document.

**Comment by fellan12** [comment]
Okey, will go through the project plan and assigne someone else to the task

**Comment by mengelin** [comment]
Done and DONE. Tack Felixnavidad <3
