### ISSUE TITLE
Mount Raspberry Pi on the Drone

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#13]
We need to find a way to safely mount the Raspberry Pi onto the Drone, preferably without making irrecoverable damage to the drone or the Pi.

Any volunteer?

**Comment by karlek** [comment]
How did the guy in the video, the one Mange sent us, mount his Raspberry Pi to the drone?

**Comment by fellan12** [comment]
I thinkt he doesn't say how he did it...

**Comment by karlek** [comment]
Is duct tape to unproffesional?

**Comment by fellan12** [comment]
we could glue the case to the drone, but do we damage it then?

**Comment by karlek** [comment]
I'm skeptic that only glue would work, but maybe. How about both gluing and duct taping it? The drones protective cover will probably be destroyed no matter what we do.

I vote only duct taping it.

**Comment by fellan12** [comment]
Ching!

**Comment by karlek** [comment]
Duct tape it is.
