### ISSUE TITLE
Correct the sample database

### ISSUE THREAD

**Issue by fellan12** [aronstrandberg/MVK15#18]
Enhance the sample database after issue #17 is closed.

**Comment by karlek** [comment]
This is on hold untill we solve #19

**Comment by aronstrandberg** [comment]
So this should be on go again now that #19 is a non-issue

**Comment by karlek** [comment]
I'm thinking about the test script that we currently have, can't we just print the generated json coordinates with document.write and save it to a file? Database insertion from the json should be trivial. @aronstrandberg what do you think?

**Comment by aronstrandberg** [comment]
From the prototype you mean? Generating random bogus GPS coordinates, yes, this should be trivial

**Comment by karlek** [comment]
Could be a first step before we complete the soldering of the GPS-unit.

**Comment by nejlika** [comment]
Still an issue?
