### ISSUE TITLE
Raspberry pi version

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#2]
Which raspberry pi version should we chose?
Any trade-offs / advantages with a specific version?

Consider:
 * Price
 * Weight
 * Module-compatibility
 * Size
 * Speed
 * etc.

**Comment by RasmusFredrikson** [comment]
Bestämde vi oss inte för att köra Raspberry pi 2?

**Comment by fellan12** [comment]
Yes, during our last meeting decided on buying Raspberry Pi 2. So we are now going to buy it!

Link to where we could buy it:
http://www.webhallen.com/se-sv/datorkomponenter/213596-raspberry_pi_2_enkortsdator
