### ISSUE TITLE
Install ruby on rails on your development computer

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#20]
For all who want to program.

Versions:
* Ruby 2.2.0
* Rails 4.2.0

Done:
- Aron
- Felix
- Martin

**Comment by fellan12** [comment]
Done!

**Comment by RasmusFredrikson** [comment]
Sandra has installed Ruby on Rails on her computer. Since she's the only one who's gonna work with Ruby on Rails I therefore close this issue.
