### ISSUE TITLE
Investigate if we want / already follow any software standards.

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#23]
This is for 3.5 in the SRS report template.

**Comment by agnesaman93** [comment]
It says "This should specify design constraints that can be imposed by other standards, hardware limitations, etc." - does MVC count?

**Comment by agnesaman93** [comment]
Rails?

**Comment by agnesaman93** [comment]
Okay, now I understand what this is! But I don't really think it is necessary

**Comment by karlek** [comment]
Cool, I'll close the shit out of this issue.
