### ISSUE TITLE
Read through the intro tutorial to rails.

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#25]
Read #24 first.

This issue is for the programmers. If you want to code, you'll need to go through the tutorial if you're not familiar with ruby. 

I'm sorry it's so lame..

Ref:
http://railsforzombies.org/

**Comment by aronstrandberg** [comment]
Official guide: http://guides.rubyonrails.org/getting_started.html

**Comment by RasmusFredrikson** [comment]
No longer necessary since we're using PHP.
