### ISSUE TITLE
Construct a list of programmers in this project

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#27]
It's easier for me to assigne issues to people if I know who wants to code.

Write in this issue if:
* you want to code,
* how much you want to code,
* how much of the tutorials you've read or
* if you got any preferences.

Sorry for that badly structured list :camel:

**Comment by aronstrandberg** [comment]
- I want to code
- I don't know. "Lagom"
- Been going through both D3 and Rails, not finished

**Comment by sandrahbackstrom** [comment]
Jag är på!

**Comment by sandrahbackstrom** [comment]
I want to code
I want like little/a few assignments because of SRS and reports
Will be doing some Rails tutorials

**Comment by fellan12** [comment]
I want to code
I want "Lagomt" with assignments
Been doing tutorials on fundamentals on js, ruby and python
Want to work on the pie 2, less/nothing on rails

**Comment by nejlika** [comment]
Since we have received the hardware a list of dedicated programmers would present a more solvable situation for delegation.

**Comment by nejlika** [comment]
I could help out with coding but will have a rather busy 4th period so my time will be limited. I've done parts/all of the Getting Started with Rails.

**Comment by agnesaman93** [comment]
I want to code.
Little - medium
Focus on frontend
Have not done any tutorials yet, but were planning to look at js this week.

**Comment by mengelin** [comment]
Pretty much exactly like Agnes. Leaning towards frontend, but anything is fine.

**Comment by RasmusFredrikson** [comment]
I want to code.
Little - Medium
Focus on Raspberry Pi
Haven't dont any tutorials yet, planning on doing them next week

**Comment by mengelin** [comment]
Nevermind what I might have said earlier. I want to code the shit out of that Raspberry Pi

**Comment by nejlika** [comment]
@shappe @Patstrom Någon input?

**Comment by RasmusFredrikson** [comment]
The programming assignments has been assigned to the project members.
