### ISSUE TITLE
Investigate D3.js

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#28]
Is it applicable to our frontend?

Ref:

http://d3js.org/

**Comment by karlek** [comment]
Progress?

**Comment by nejlika** [comment]
Current issue that Aron doesn't have access to a substatial source of GeoJSON data, could be solved once we have access to the GPS.

**Comment by nejlika** [comment]
We have recieved input from HiQ regarding the use of D3.js, they seem to be adamant that we use D3.

**Comment by karlek** [comment]
To further specify what HiQ wants to use D3.js for: each node in our map view should be clickable and information about the current, previous and next nodes should be used to compute some values and be displayed with D3.js

**Comment by nejlika** [comment]
To add on the issue, check wether or not we can expose CartoDB to D3.
http://cartodb.com/

**Comment by sandrahbackstrom** [comment]
Can close?
