### ISSUE TITLE
Protective case

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#3]
**Depends on raspberry pi version!**

Discuss later.

**Comment by fellan12** [comment]
Now that we have made the decision on buying the Pi 2, we have the option on where to buy the protective case for the Pi.

Links to where to buy the case:
http://www.adafruit.com/products/2285

http://www.webhallen.com/se-sv/datorkomponenter/208483-raspberry_pi_type_b_case-clear
