### ISSUE TITLE
Formula to calculate velocity and acceleration

### ISSUE THREAD

**Issue by aronstrandberg** [aronstrandberg/MVK15#31]
We need a formula to calculate velocity and/or acceleration (and anything else interesting we can, maybe x- and y-axis velocity?) based on only current **x- and y-axis gps coordinate** and **timestamp**. This is ready to implement in the prototype, so let's get it done so we can have it ready in time for the meeting with HiQ!

Assigned @mengelin but if anyone else feels up to it, go!

**Comment by fellan12** [comment]
You cant calculate velocity, yet acceleration based on only one set of GPS points, you will need atleast two sets for velocity and 4 sets for acceleration.

**Comment by aronstrandberg** [comment]
Sorry, current and all previous is what I mean of course

**Comment by karlek** [comment]
Closely related to #36

**Comment by sandrahbackstrom** [comment]
Irrelevant as we use the speed function in the GPS? Can close?
