### ISSUE TITLE
Configure the Pi's wifi device

### ISSUE THREAD

**Issue by nejlika** [aronstrandberg/MVK15#34]
As of writing, the wifi-unit on the Pi can only connect to Felix's phone, this might cause complications.

Fix a "general" solution.

**Comment by karlek** [comment]
Have we tried other phones? Or why didn't it work? Couldn't connect to the hotspot, couldn't the Pi find the HS, etc?

**Comment by fellan12** [comment]
I have now configured the Pi for a few phones, but for the few of you left, find me in META and I'll synchronize your phone to the Pi.

**Comment by nejlika** [comment]
We know how to grant access to the Pi, closing issue.
