### ISSUE TITLE
Strategy for debugging

### ISSUE THREAD

**Issue by nejlika** [aronstrandberg/MVK15#35]
We need a managable solution for bug detection and solution, such as the backlog in SCRUM.

**Comment by karlek** [comment]
@aronstrandberg we are currently not using any js libraries right? Can't we just use console.log for all diagnostic output and also write tests for our js functions?

**Comment by aronstrandberg** [comment]
Just jQuery right now, plus D3 once we get started obviously. I'm sure there is something nice out there, don't know anything but shout if you find any

**Comment by karlek** [comment]
Should we just silently close this issue..?

**Comment by aronstrandberg** [comment]
Rubber ducking yo ducksarethebest.com

Closing
