### ISSUE TITLE
Create UML-diagrams

### ISSUE THREAD

**Issue by nejlika** [aronstrandberg/MVK15#38]
The SRS requires a visual representation of the system. Björn recommended, and I agree, using UML.

Create a draft of controlflow for both front-end and back-end which can be improved iteratively.

This is a issue directed at @aronstrandberg and @karlek

**Comment by karlek** [comment]
Was the UML-lecture any good?

**Comment by aronstrandberg** [comment]
Was anyone there?

**Comment by fellan12** [comment]
Aron have u made your sequence diagram yet?

**Comment by RasmusFredrikson** [comment]
All the UML-diagrams are done. Closing the issue.

**Comment by nejlika** [comment]
Update UML:s to reflect the current structure:
@karlek: Backend, [old](https://files.slack.com/files-pri/T03HNB08S-F0443N7BB/backend_-_page_1.png)
@fellan12: Raspberry Pi, [old](https://files.slack.com/files-pri/T03HNB08S-F04474ML1/mvk_raspberry_pi_uml.png)
@aronstrandberg: Frontend, [old](https://files.slack.com/files-pri/T03HNB08S-F044N0JMR/untitled_document_-_new_page.png)

**Comment by karlek** [comment]
Hai! Does anyone remember what site we used to make these? Looks cleaner with consistent design

**Comment by nejlika** [comment]
@karlek Lucidcharts maybe?

**Comment by karlek** [comment]
Ty.

**Comment by RasmusFredrikson** [comment]
The UML-diagrams are done. Closing.
