### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#4]
**Depends on raspberry pi version!**

Which battery should we chose?

Consider:
* Price
* Weight
* Size
* Battery time
* Port
* etc.

**Comment by fellan12** [comment]
When is comes to battery pack for the Pi there is a lot of pack, but they all weigh a lot. 
On adafruit's website there is a "USB Battery Pack for Raspberry Pi - 4400mAh - 5V @ 1A" that weighs 140g. And that pack should keep the Pi supplied with power for 5 hour, if it has "headless" i.e no keyboard, mouse or display attached.

USB Battery Pack for Raspberry Pi - 4400mAh - 5V @ 1A: 140g (http://www.adafruit.com/products/1565)

**Comment by fellan12** [comment]
Should we go for it?

**Comment by karlek** [comment]
We don't need more than 1 hour considering we only have 36 minutes of flight time without the Raspberry Pi mounted. So maybe an even lighter battery pack would be preferable.

**Comment by fellan12** [comment]
I will keep looking!

**Comment by karlek** [comment]
Do you think the USB WiFi drains much battery?

**Comment by nejlika** [comment]
What about supply-time for a Pi with sensors and wifi-connection? Would the batterytime be affected by those?

**Comment by fellan12** [comment]
Yes given that we will have a GPS and Wifi, the battery time will be less than 5 hour given the battery pack i previously told about.

I should i look for a smaller one or should we take the bigger one?

**Comment by karlek** [comment]
Would suck if the battery was to small and 140g is okay. I say go for it. Post the link to the battery and close the issue. Nicely done :)

**Comment by fellan12** [comment]
So the battery pack we will buy for the Pi 2 is:

USB Battery Pack for Raspberry Pi - 4400mAh - 5V @ 1A: 140g (http://www.adafruit.com/products/1565)

**Comment by fellan12** [comment]
New battery pack from webhallen:
http://www.webhallen.com/se-sv/mobilt/192992-deltaco_powerbank_portablet_batteri_for_laddning_av_mobila_enheter_5000mah_usb_5v_21a&atcl=search:result

Can someone check if this one works better weight and powerwise?

**Comment by nejlika** [comment]
tech|Adafruit | Webhallen
-----|------|------------------
output| 1 A | 2.1 A
batterysize| 4400 mAh|5000 mAh
weight (excluding cables)| 140 g | 139 g
size| 96.6 cm^3| 138.45 cm^3

The power of the one from Webhallen is superior to Adafruit's, but we have a 45% increase in physical size. But seeing as the weight is roughly equal I don't see an issue with the actual size, or is it something we have to take into account?
