### ISSUE TITLE
Create a script to insert data into the database

### ISSUE THREAD

**Issue by fellan12** [aronstrandberg/MVK15#41]
Create a python script that make a insertion query to the database, without using ssh.

**Comment by aronstrandberg** [comment]
Why not SSH?

**Comment by fellan12** [comment]
I think it's better if we can insert directly to the database. Having SSH requires us to hard code the VM's login information and password, with in my head could cause some security issues.

**Comment by fellan12** [comment]
Martin, consult with aron on how to proceed involving the script.

**Comment by fellan12** [comment]
@mengelin did you get this!

**Comment by nejlika** [comment]
Aren't all the security regarding login solved by the whitelist?

**Comment by mengelin** [comment]
Umm no Felix. It doesn't require us to hard code the login information into the script. You can just enter it into the terminal as a part of the script. I hardcoded it into the script simply to save time when testing it.

**Comment by mengelin** [comment]
We could use VNC to control the pi while flying. Starting and stoping a lap aswell as using ssh to the VM. Right?

**Comment by nejlika** [comment]
Yes @mengelin, that could be a solution. How stable is VNC in the wild?

**Comment by mengelin** [comment]
Wouldn't be any different from what it is when we have tested it in Meta, since we are using wi-fi hotspot for VNC

**Comment by sandrahbackstrom** [comment]
done?

**Comment by karlek** [comment]
Done!
