### ISSUE TITLE
When the Pi is offline, the website will display the last recorded lap

### ISSUE THREAD

**Issue by nejlika** [aronstrandberg/MVK15#44]

**Comment by karlek** [comment]
Simple fix in the PHP file; select max lap id.

**Comment by aronstrandberg** [comment]
How will I know whether the Pi is offline from js?

**Comment by karlek** [comment]
You won't, since the query will always return the maximum lap id (i.e the most recent). Fixed in my local version. Will close when I push.

**Comment by karlek** [comment]
Missclick lol.

**Comment by karlek** [comment]
However it would be nice if the UI changed color or at least indicated if the drone is active... But that's another issue.
