### ISSUE TITLE
3G/4G/WiFi-dongle

### ISSUE THREAD

**Issue by karlek** [aronstrandberg/MVK15#5]
**Depends on raspberry pi version!**

Which 3G/4G/WiFi-dongle should we chose?

__Post links for suggestions of 3G/4G/WiFi-dongles.__

Consider:
* Port
* Price
* Ease of installation
* Recommended by the Raspberry Pi community

Installing and configuring 3G/4G/WiFi on the raspberry pi, can be more challenging than you think. Linux / command-line experience is recommended. 

Any volunteer?

**Comment by karlek** [comment]
What's the status here: is the consensus that 3G-dongle doesn't work on the Raspberry Pi because we can't have a powered USB-hub? 

So then our only option is WiFi / Shared hotspot with a phone?

**Comment by nejlika** [comment]
3G-dongle is not viable due to power solutions; the drone can't carry a large enough battery to support the system.

Use this:
http://www.adafruit.com/products/814

**Comment by aronstrandberg** [comment]
Have we consulted HiQ regarding this?

**Comment by nejlika** [comment]
They proposed a product where the drone flies between hotspots (their own example is a phone). Our solution could use stationary "loading points" for the data transfer but this might be sub-par.
