### ISSUE TITLE
Complete infobox display

### ISSUE THREAD

**Issue by aronstrandberg** [aronstrandberg/MVK15#53]
The info box in the lower right corner needs to be completed, given input data

**Comment by karlek** [comment]
The updated version of the database contains altitude and velocity.

**Comment by aronstrandberg** [comment]
Dun, will push with the next commit.

**Comment by aronstrandberg** [comment]
Not done, this includes styling as well

**Comment by nejlika** [comment]
But but, you said dun!

**Comment by aronstrandberg** [comment]
No I didn't? :stuck_out_tongue:

**Comment by RasmusFredrikson** [comment]
The styling has been done. Closing.
