### ISSUE TITLE
Only request new data points

### ISSUE THREAD

**Issue by aronstrandberg** [aronstrandberg/MVK15#57]
When fetching new data, only retrieve new ones instead of fetching everything

**Comment by sandrahbackstrom** [comment]
This is done in the PHP program? 
We added an attribute called "Read" and we fetch the rows in which the read is 0 and update them to 1. Then we only get the new ones. @aronstrandberg

**Comment by aronstrandberg** [comment]
@karlek and I came up with a better solution, which is to send the maximum previously received id with the GET request, and then respond only with the ids which are greater. This means I have to keep track of this in the js code as well.
