### ISSUE TITLE
Point colors should not be so ugly

### ISSUE THREAD

**Issue by aronstrandberg** [aronstrandberg/MVK15#58]
Would look better if they're more toned down

**Comment by karlek** [comment]
Change the size of the dot to represent speed and only use black / cerise color scheme? Or if we use multiple colors AND change the size of the dots we could both represent altitude and velocity!

**Comment by karlek** [comment]
Colors of the dots should be dark gray unless hovered. And find a good color scheme. The size of the big dots should represent the altitude. Small dots are always the same size.

**Comment by aronstrandberg** [comment]
It's quite problematic to estimate the top velocity until we make a test flight with the drone.

**Comment by sandrahbackstrom** [comment]
Looks good to me!
