### ISSUE TITLE
Only draw every n:th point

### ISSUE THREAD

**Issue by aronstrandberg** [aronstrandberg/MVK15#59]
Draw lines or smaller dots in between?

**Comment by karlek** [comment]
Whichever is easier. I think it would be smaller dots, then you just need to save the last big dot and calculate the distance from it. 

However lines are much more clear which path was taken in case the drone crosses it's own path.

**Comment by karlek** [comment]
Either every n point is a large point. However this forces us to only indicate altitude on the large dots by size.

**Comment by aronstrandberg** [comment]
Dun, will push with next commit.
