### ISSUE TITLE
Remove bars as the number increases?

### ISSUE THREAD

**Issue by aronstrandberg** [aronstrandberg/mvk15#61]
Looks very crowded when the number of bars becomes high. Will possibly improve when the height of the bars isn't random

**Comment by karlek** [comment]
Possible solutions, only the latest n-points. Only every n-th point of all points. Random n points. etc.

**Comment by karlek** [comment]
It's quite bad if the bars move / change during flight if you want to hover over them... I can imagine it would be quite frustrating.

**Comment by karlek** [comment]
Fixed number of bars. In the beginning a few bars will have info and the rest will be a very low value and a different color. Then they will rise up bullshit etc.

The selection of the points should be last 20. Future update might change this selection or offer a setting.

**Comment by nejlika** [comment]
If we choose a solution where we only plot the latest n points, there should be an option to display the whole lap after it's completion.

**Comment by aronstrandberg** [comment]
y u gon b such a bitch

**Comment by nejlika** [comment]
'cuz if I don tell u, hiq be mad

**Comment by aronstrandberg** [comment]
![(╯°□°）╯︵ ┻━┻](http://www.reactiongifs.com/r/flip.gif)

**Comment by karlek** [comment]
@nejlika we mean in the graph view, not the plotted points.

**Comment by karlek** [comment]
Not prio atm.

**Comment by sandrahbackstrom** [comment]
Could be scrolling the graph from left to right and right to left instead of removing
