### ISSUE TITLE
Test that the website can retrive data from database via php

### ISSUE THREAD

**Issue by sandrahbackstrom** [aronstrandberg/MVK15#63]

**Comment by fellan12** [comment]
@aronstrandberg does it work now?

**Comment by aronstrandberg** [comment]
Haha, you don't trust me? I tested it before I said it was working. It works.

**Comment by aronstrandberg** [comment]
Or is this some SRS official thingie? In that case, go nuts

**Comment by karlek** [comment]
I do a Sandra.
Close :D
